name: ci

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, 'doc:')"
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        target: [12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git log
        shell: bash
        run: |
          if [ -n "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+')" ]; then
            echo "CI_SKIP=true" >> $GITHUB_ENV
          fi

          echo "TEST=true" >> $GITHUB_ENV

          echo "github.ref: ${{ github.ref }}"
          echo "github.event.ref: ${{ github.event.ref }}"
          echo "glo: $(git log --format=%B -n 1)"
          echo "env: ${{ env.CI_SKIP }} ${{ env.CI_SKIP == 'false' }}"
          echo "env2: ${{ env.CI_SKIP != 'true' }} ${{ env.CI_SKIP != true }}"
          echo "env3: ${{ env.TEST }} ${{ env.TEST == true }} ${{ env.TEST == 'true' }}"

      - name: Setup node@${{ matrix.target }}
        if: env.CI_SKIP == 'false'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.target }}

      - name: List versions
        shell: bash
        continue-on-error: true
        if: env.CI_SKIP == 'false'
        run: |
          node -v && npm -v && which npm

      - name: Install dependencies
        if: env.CI_SKIP == 'false'
        run: |
          npm ci --quiet

      - name: Lint
        if: env.CI_SKIP == 'false'
        run: |
          npm run lint

      - name: Build
        if: env.CI_SKIP == 'false'
        run: |
          npm run build:test

      - name: Check build
        shell: bash
        if: env.CI_SKIP == 'false'
        run: |
          pwd && ls -la

      - name: Test
        if: env.CI_SKIP == 'false'
        run: |
          npm run jest

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        if: env.CI_SKIP == 'false' && success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unit_tests
